config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    unauthenticated do
      root to: 'users/sessions#new'
    end
  end

  resources :questions do
    resources :options
    resources :selections
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

end

app/models/option.rb
class Option
  include Mongoid::Document
  include Mongoid::Timestamps::Short
  field :name
  belongs_to :question
end

app/models/question.rb
class Question
  include Mongoid::Document
  include Mongoid::Timestamps::Short
  field :title, type: String
  field :description, type: String
  has_many :options
  embeds_many :selections
  accepts_nested_attributes_for :selections
end

app/models/selection.rb
class Selection
  include Mongoid::Document
  include Mongoid::Timestamps::Short
  belongs_to :user
  has_and_belongs_to_many :options, inverse_of: nil
  embedded_in :question, inverse_of: :selections
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time

  field :name

  def valid_password?(password)
    true
  end

  protected
    def password_required?
      false
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  before_action :set_question

  respond_to :html

  def create
    @option = @question.options.new(option_params)
    @option.save
    respond_with(@question)
  end

  private
    def set_question
      @question = Question.find(params[:question_id])
    end

    def option_params
      params.require(:option).permit(:name)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @questions = Question.all
    respond_with(@questions)
  end

  def show
    respond_with(@question)
  end

  def new
    @question = Question.new
    respond_with(@question)
  end

  def edit
  end

  def create
    @question = Question.new(question_params)
    @question.save
    respond_with(@question)
  end

  def update
    @question.update(question_params)
    respond_with(@question)
  end

  def destroy
    @question.destroy
    respond_with(@question)
  end

  private
    def set_question
      @question = Question.find(params[:id])
    end

    def question_params
      params.require(:question).permit(:title, :description)
    end
end

app/controllers/selections_controller.rb
class SelectionsController < ApplicationController
  before_action :set_question
  before_action :set_selection, only: [:update]

  respond_to :html

  def create
    @selection = @question.selections.new(selection_params)
    @selection.user = current_user
    @selection.save
    respond_with(@question)
  end

  def update
    begin
      @selection.update(selection_params)
    rescue ActionController::ParameterMissing
      @selection.destroy
    end
    respond_with(@question)
  end

  private
    def set_question
      @question = Question.find(params[:question_id])
    end

    def set_selection
      @selection = @question.selections.find(params[:id])
    end

    def selection_params
      params.require(:selection).permit(option_ids: [])
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_sign_up_params, only: [:create]
  before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # You can put the params you want to permit in the empty array.
  def configure_sign_up_params
    devise_parameter_sanitizer.for(:sign_up) << :name
  end

  # You can put the params you want to permit in the empty array.
  def configure_account_update_params
    devise_parameter_sanitizer.for(:account_update) << :name
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Survey
    = viewport_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top{role: 'navigation'}
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{type:'button', data: { toggle: 'collapse', target: '.navbar-collapse'}}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{href:'#'} Survey
        .collapse.navbar-collapse
          %ul.nav.navbar-nav
            - if user_signed_in?
              %li= link_to 'Logout', destroy_user_session_path, method: :delete
            - else
              %li= link_to 'Login', new_user_session_path
    .container
      .row
        = bootstrap_flash
        = yield

app/views/questions/_form.html.haml
= form_for @question do |f|
  - if @question.errors.any?
    #error_explanation
      %h2= "#{pluralize(@question.errors.count, "error")} prohibited this question from being saved:"
      %ul
        - @question.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_field :description
  .actions
    = f.submit 'Save'

app/views/questions/_selection.html.haml
- selection = question.selections.where(user: current_user).first_or_initialize
= form_for [question, selection], role: 'form' do |f|
  - question.options.each do |option|
    .form-group.input-group
      %span.input-group-addon
        %input.checkbox{type: 'checkbox', name:'selection[option_ids][]', value: option.id, checked: selection.options.where(_id: option).exists?}
      %p.form-control.form-control-static
        = option.name
      %span.input-group-addon
        %span.badge= question.selections.in(option_ids: option).size

app/views/questions/edit.html.haml
%h1 Editing question

= render 'form'

= link_to 'Show', @question
\|
= link_to 'Back', questions_path

app/views/questions/index.html.haml
%h1 Listing questions

%table
  %tr
    %th Title
    %th Description
    %th
    %th
    %th

  - @questions.each do |question|
    %tr
      %td= question.title
      %td= question.description
      %td= link_to 'Show', question
      %td= link_to 'Edit', edit_question_path(question)
      %td= link_to 'Destroy', question, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Question', new_question_path

app/views/questions/new.html.haml
%h1 New question

= render 'form'

= link_to 'Back', questions_path

app/views/questions/show.html.haml
.col-md-12
  .row
    .col-md-12
      .panel.panel-info
        .panel-heading
          %h4.panel-title= @question.title
        .panel-body
          :markdown
            #{@question.description}
        .panel-footer
          %p Response
          - response = @question.selections.size * 100 / User.all.size
          .progress
            .progress-bar.progress-bar-striped.active{role: 'progressbar', style: "width: #{response}%;"}
            .progress-bar.progress-bar-striped.active.progress-bar-danger{role: 'progressbar', style: "width: #{100-response}%;"}
  .row
    .col-md-4
      .panel.panel-primary
        .panel-heading
          %h4.panel-title
            Your Choice
        .panel-body
          = render 'questions/selection', question: @question
          = form_for [@question, @question.options.new] do |f|
            .form-group.input-group
              %span.input-group-addon
                %input.checkbox.disabled{type: 'checkbox', disabled: true}
              = f.text_field :name, class: 'form-control', placeholder: 'Type new option...'
              %span.input-group-btn
                %button.btn.btn-default
                  = glyph 'plus'
    .col-md-8
      .panel.panel-default
        .panel-heading
          %h4.panel-title
            Survey Status
        %table.table
          %tr
            %th Name
            %th Choice
          - @question.selections.each do |selection|
            = render selection

app/views/selections/_selection.html.haml
%tr
  %td
    = selection.user.name
  %td
    %ul.list-inline
      - selection.options.each do |option|
        %li= option.name

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>